version: 1.0
name: Note Service
description: A service for managing notes with PostgreSQL
author: togashi tomohiro

settings:
  PORT: 8082
  ENV: development

database:
  host: localhost
  port: 5432
  user: noteuser
  password: notepass
  dbname: notedb
  sslmode: disable
