server:
  port: 50053

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  name: auth_db
  ssl_mode: disable

jwt:
  secret_key: your-secret-key-change-this-in-production
  token_duration_hours: 24

mailer:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com
  password: your-app-password
  from: your-email@gmail.com
