version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: note_postgres
    environment:
      POSTGRES_DB: notedb
      POSTGRES_USER: noteuser
      POSTGRES_PASSWORD: notepass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noteuser -d notedb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
