// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/api/memo.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Memo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memo) Reset() {
	*x = Memo{}
	mi := &file_proto_api_memo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memo) ProtoMessage() {}

func (x *Memo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memo.ProtoReflect.Descriptor instead.
func (*Memo) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{0}
}

func (x *Memo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Memo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Memo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Memo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoRequest) Reset() {
	*x = CreateMemoRequest{}
	mi := &file_proto_api_memo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoRequest) ProtoMessage() {}

func (x *CreateMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoRequest.ProtoReflect.Descriptor instead.
func (*CreateMemoRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMemoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMemoRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *Memo                  `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoResponse) Reset() {
	*x = CreateMemoResponse{}
	mi := &file_proto_api_memo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoResponse) ProtoMessage() {}

func (x *CreateMemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoResponse.ProtoReflect.Descriptor instead.
func (*CreateMemoResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMemoResponse) GetMemo() *Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type CreateMemoByJsonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoByJsonRequest) Reset() {
	*x = CreateMemoByJsonRequest{}
	mi := &file_proto_api_memo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoByJsonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoByJsonRequest) ProtoMessage() {}

func (x *CreateMemoByJsonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoByJsonRequest.ProtoReflect.Descriptor instead.
func (*CreateMemoByJsonRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMemoByJsonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMemoByJsonRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMemoByJsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *Memo                  `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoByJsonResponse) Reset() {
	*x = CreateMemoByJsonResponse{}
	mi := &file_proto_api_memo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoByJsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoByJsonResponse) ProtoMessage() {}

func (x *CreateMemoByJsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoByJsonResponse.ProtoReflect.Descriptor instead.
func (*CreateMemoByJsonResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMemoByJsonResponse) GetMemo() *Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type GetMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoRequest) Reset() {
	*x = GetMemoRequest{}
	mi := &file_proto_api_memo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoRequest) ProtoMessage() {}

func (x *GetMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoRequest.ProtoReflect.Descriptor instead.
func (*GetMemoRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{5}
}

func (x *GetMemoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *Memo                  `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoResponse) Reset() {
	*x = GetMemoResponse{}
	mi := &file_proto_api_memo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoResponse) ProtoMessage() {}

func (x *GetMemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoResponse.ProtoReflect.Descriptor instead.
func (*GetMemoResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{6}
}

func (x *GetMemoResponse) GetMemo() *Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type GetMultiMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoIds       []string               `protobuf:"bytes,1,rep,name=memo_ids,json=memoIds,proto3" json:"memo_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultiMemoRequest) Reset() {
	*x = GetMultiMemoRequest{}
	mi := &file_proto_api_memo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultiMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultiMemoRequest) ProtoMessage() {}

func (x *GetMultiMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultiMemoRequest.ProtoReflect.Descriptor instead.
func (*GetMultiMemoRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{7}
}

func (x *GetMultiMemoRequest) GetMemoIds() []string {
	if x != nil {
		return x.MemoIds
	}
	return nil
}

type GetMultiMemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *Memo                  `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultiMemoResponse) Reset() {
	*x = GetMultiMemoResponse{}
	mi := &file_proto_api_memo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultiMemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultiMemoResponse) ProtoMessage() {}

func (x *GetMultiMemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultiMemoResponse.ProtoReflect.Descriptor instead.
func (*GetMultiMemoResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{8}
}

func (x *GetMultiMemoResponse) GetMemo() *Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type ListMemosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemosRequest) Reset() {
	*x = ListMemosRequest{}
	mi := &file_proto_api_memo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemosRequest) ProtoMessage() {}

func (x *ListMemosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemosRequest.ProtoReflect.Descriptor instead.
func (*ListMemosRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{9}
}

func (x *ListMemosRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListMemosRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ListMemosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memos         []*Memo                `protobuf:"bytes,1,rep,name=memos,proto3" json:"memos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemosResponse) Reset() {
	*x = ListMemosResponse{}
	mi := &file_proto_api_memo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemosResponse) ProtoMessage() {}

func (x *ListMemosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemosResponse.ProtoReflect.Descriptor instead.
func (*ListMemosResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{10}
}

func (x *ListMemosResponse) GetMemos() []*Memo {
	if x != nil {
		return x.Memos
	}
	return nil
}

type UpdateMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemoRequest) Reset() {
	*x = UpdateMemoRequest{}
	mi := &file_proto_api_memo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemoRequest) ProtoMessage() {}

func (x *UpdateMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemoRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemoRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMemoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMemoRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateMemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *Memo                  `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemoResponse) Reset() {
	*x = UpdateMemoResponse{}
	mi := &file_proto_api_memo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemoResponse) ProtoMessage() {}

func (x *UpdateMemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_memo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemoResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemoResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_memo_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMemoResponse) GetMemo() *Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

var File_proto_api_memo_proto protoreflect.FileDescriptor

const file_proto_api_memo_proto_rawDesc = "" +
	"\n" +
	"\x14proto/api/memo.proto\x12\x04memo\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x01\n" +
	"\x04Memo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"C\n" +
	"\x11CreateMemoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"4\n" +
	"\x12CreateMemoResponse\x12\x1e\n" +
	"\x04memo\x18\x01 \x01(\v2\n" +
	".memo.MemoR\x04memo\"I\n" +
	"\x17CreateMemoByJsonRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\":\n" +
	"\x18CreateMemoByJsonResponse\x12\x1e\n" +
	"\x04memo\x18\x01 \x01(\v2\n" +
	".memo.MemoR\x04memo\" \n" +
	"\x0eGetMemoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x0fGetMemoResponse\x12\x1e\n" +
	"\x04memo\x18\x01 \x01(\v2\n" +
	".memo.MemoR\x04memo\"0\n" +
	"\x13GetMultiMemoRequest\x12\x19\n" +
	"\bmemo_ids\x18\x01 \x03(\tR\amemoIds\"6\n" +
	"\x14GetMultiMemoResponse\x12\x1e\n" +
	"\x04memo\x18\x01 \x01(\v2\n" +
	".memo.MemoR\x04memo\"\xaa\x01\n" +
	"\x10ListMemosRequest\x12>\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x88\x01\x01B\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"5\n" +
	"\x11ListMemosResponse\x12 \n" +
	"\x05memos\x18\x01 \x03(\v2\n" +
	".memo.MemoR\x05memos\"=\n" +
	"\x11UpdateMemoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"4\n" +
	"\x12UpdateMemoResponse\x12\x1e\n" +
	"\x04memo\x18\x01 \x01(\v2\n" +
	".memo.MemoR\x04memo2\xa0\x03\n" +
	"\vMemoService\x12?\n" +
	"\n" +
	"CreateMemo\x12\x17.memo.CreateMemoRequest\x1a\x18.memo.CreateMemoResponse\x12Q\n" +
	"\x10CreateMemoByJson\x12\x1d.memo.CreateMemoByJsonRequest\x1a\x1e.memo.CreateMemoByJsonResponse\x126\n" +
	"\aGetMemo\x12\x14.memo.GetMemoRequest\x1a\x15.memo.GetMemoResponse\x12F\n" +
	"\rGetMultiMemos\x12\x19.memo.GetMultiMemoRequest\x1a\x1a.memo.GetMultiMemoResponse\x12<\n" +
	"\tListMemos\x12\x16.memo.ListMemosRequest\x1a\x17.memo.ListMemosResponse\x12?\n" +
	"\n" +
	"UpdateMemo\x12\x17.memo.UpdateMemoRequest\x1a\x18.memo.UpdateMemoResponseB\n" +
	"Z\bapp/grpcb\x06proto3"

var (
	file_proto_api_memo_proto_rawDescOnce sync.Once
	file_proto_api_memo_proto_rawDescData []byte
)

func file_proto_api_memo_proto_rawDescGZIP() []byte {
	file_proto_api_memo_proto_rawDescOnce.Do(func() {
		file_proto_api_memo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_memo_proto_rawDesc), len(file_proto_api_memo_proto_rawDesc)))
	})
	return file_proto_api_memo_proto_rawDescData
}

var file_proto_api_memo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_api_memo_proto_goTypes = []any{
	(*Memo)(nil),                     // 0: memo.Memo
	(*CreateMemoRequest)(nil),        // 1: memo.CreateMemoRequest
	(*CreateMemoResponse)(nil),       // 2: memo.CreateMemoResponse
	(*CreateMemoByJsonRequest)(nil),  // 3: memo.CreateMemoByJsonRequest
	(*CreateMemoByJsonResponse)(nil), // 4: memo.CreateMemoByJsonResponse
	(*GetMemoRequest)(nil),           // 5: memo.GetMemoRequest
	(*GetMemoResponse)(nil),          // 6: memo.GetMemoResponse
	(*GetMultiMemoRequest)(nil),      // 7: memo.GetMultiMemoRequest
	(*GetMultiMemoResponse)(nil),     // 8: memo.GetMultiMemoResponse
	(*ListMemosRequest)(nil),         // 9: memo.ListMemosRequest
	(*ListMemosResponse)(nil),        // 10: memo.ListMemosResponse
	(*UpdateMemoRequest)(nil),        // 11: memo.UpdateMemoRequest
	(*UpdateMemoResponse)(nil),       // 12: memo.UpdateMemoResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_proto_api_memo_proto_depIdxs = []int32{
	13, // 0: memo.Memo.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: memo.Memo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: memo.CreateMemoResponse.memo:type_name -> memo.Memo
	0,  // 3: memo.CreateMemoByJsonResponse.memo:type_name -> memo.Memo
	0,  // 4: memo.GetMemoResponse.memo:type_name -> memo.Memo
	0,  // 5: memo.GetMultiMemoResponse.memo:type_name -> memo.Memo
	13, // 6: memo.ListMemosRequest.start_time:type_name -> google.protobuf.Timestamp
	13, // 7: memo.ListMemosRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 8: memo.ListMemosResponse.memos:type_name -> memo.Memo
	0,  // 9: memo.UpdateMemoResponse.memo:type_name -> memo.Memo
	1,  // 10: memo.MemoService.CreateMemo:input_type -> memo.CreateMemoRequest
	3,  // 11: memo.MemoService.CreateMemoByJson:input_type -> memo.CreateMemoByJsonRequest
	5,  // 12: memo.MemoService.GetMemo:input_type -> memo.GetMemoRequest
	7,  // 13: memo.MemoService.GetMultiMemos:input_type -> memo.GetMultiMemoRequest
	9,  // 14: memo.MemoService.ListMemos:input_type -> memo.ListMemosRequest
	11, // 15: memo.MemoService.UpdateMemo:input_type -> memo.UpdateMemoRequest
	2,  // 16: memo.MemoService.CreateMemo:output_type -> memo.CreateMemoResponse
	4,  // 17: memo.MemoService.CreateMemoByJson:output_type -> memo.CreateMemoByJsonResponse
	6,  // 18: memo.MemoService.GetMemo:output_type -> memo.GetMemoResponse
	8,  // 19: memo.MemoService.GetMultiMemos:output_type -> memo.GetMultiMemoResponse
	10, // 20: memo.MemoService.ListMemos:output_type -> memo.ListMemosResponse
	12, // 21: memo.MemoService.UpdateMemo:output_type -> memo.UpdateMemoResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_api_memo_proto_init() }
func file_proto_api_memo_proto_init() {
	if File_proto_api_memo_proto != nil {
		return
	}
	file_proto_api_memo_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_memo_proto_rawDesc), len(file_proto_api_memo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_memo_proto_goTypes,
		DependencyIndexes: file_proto_api_memo_proto_depIdxs,
		MessageInfos:      file_proto_api_memo_proto_msgTypes,
	}.Build()
	File_proto_api_memo_proto = out.File
	file_proto_api_memo_proto_goTypes = nil
	file_proto_api_memo_proto_depIdxs = nil
}
